config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  before_save :make_email_downcase

  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum:3, maximum:25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum:105}, format: {with: VALID_EMAIL_REGEX}
  has_secure_password

  private

  def make_email_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    if !logged_in?
      flash[:warning] = "You need to be logged in to perform this action."
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in, except: [:index, :show]
  before_action :require_the_author, only: [:edit, :destroy]

  def index
    @articles = Article.all
  end

  def show

  end

  def new
    @article = Article.new
  end

  def edit

  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      flash[:success] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_the_author
    if current_user != @article.user
      flash[:warning] = "You do not have permission to edit this article."
      redirect_to article_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Login successful"
      redirect_to user
    else
      flash.now[:warning] = "There was something wrong with your credentials"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "User logged out successfully."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in, only: [:edit, :update, :destroy]
  before_action :require_account_owner, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @articles = @user.articles
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User created successfully."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account information was updated successfully."
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_account_owner
    if current_user != @user
      flash[:warning] = "You are not allowed to perform this action"
      redirect_to user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username)
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles_list.html.erb
<h1 class="display-1">Articles</h1>
<% @articles.each do |a| %>
<div class="row">
  <div class="row">
    <div class="col-8 mt-4">
      <div class="card shadow mb-5 bg-body rounded">
        <div class="card-header">
          Author: <%= a.user.username if a.user %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to a.title, article_path(a), class: "text-primary" %></h5>
          <p class="card-text"><%= truncate(a.description, length: 150) %></p>
          <%= link_to 'View', article_path(a), class: "btn btn-outline-primary" %>
          <% if logged_in? && current_user == a.user %>
          <%= link_to 'Edit', edit_article_path(a), class: "btn btn-outline-warning" %>
          <%= link_to 'Delete', article_path(a), method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure?" } %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(a.created_at) %> ago, updated <%= time_ago_in_words(a.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'layouts/errors', obj: @article %>

<%= form_with(model: @article, local: true, class: "shadow col-10 border mt-4 p-4") do |f| %>

<div class="mb-3">
  <%= f.label :title, class: "form-label" %>
  <%= f.text_field :title, class: "form-control form-control-lg" %>
</div>

<div class="mb-3">
  <%= f.label :description, class: "form-label" %>
  <%= f.text_area :description, class: "form-control form-control-lg", rows: "10" %>
</div>

<%= f.submit(@article.new_record? ? "Create a new article" : "Update this article", class: "btn btn-success") %> <%= link_to "Cancel", articles_path, class: "btn btn-secondary" %>
<% end %>

app/views/articles/edit.html.erb
<h1 class="display-1">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<%= render 'articles_list' %>

app/views/articles/new.html.erb
<h1 class="display-1">New article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="display-1"><%= @article.title %></h1>
<p><%= @article.description %></p>
<% if logged_in? && current_user == @article.user %>
<%= link_to 'Edit this article', edit_article_path(@article), class: "btn btn-warning" %>
<%= link_to 'Delete', article_path(@article), method: :delete, class:"btn btn-danger", data: { confirm: "Are you sure?" } %>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger col-10" role="alert">
  <h3>Errors, when creating <%= obj.class.name.downcase %>:</h3>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>" role="alert">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Touhid Test Blog', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Authors', users_path, class: 'nav-link'%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'List of articles', articles_path, class: 'dropdown-item'%></li>
            <% if logged_in? %>
              <li><%= link_to 'Create a new article', new_article_path, class: 'dropdown-item'%></li>
            <% end %>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'Your profile', user_path(current_user), class: 'dropdown-item' %></li>
            <li><%= link_to 'Logout', logout_path, class: 'dropdown-item', method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TouhidTestBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="display-1">This is the About page</h1>

app/views/pages/home.html.erb
<div class="card bg-dark text-white mt-4">
  <%= image_tag("blog_home_bg.jpg", alt: "Test blog", class: "card-img", height: "450") %>
  <div class="card-img-overlay text-center mt-4">
    <h1 class="display-1">Welcome to this test blog.</h1>
    <p>This is done as part of a training course on ruby on rails.</p>
    <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/users/_form.html.erb
<%= render 'layouts/errors', obj: @user %>

<%= form_with(model: @user, local: true, class: "shadow col-10 border mt-4 p-4") do |f| %>

  <div class="mb-3">
    <%= f.label :username, class: "form-label" %>
    <%= f.text_field :username, class: "form-control form-control-lg", placeholder: "Enter your username" %>
  </div>
  <div class="mb-3">
    <%= f.label :email, class: "form-label" %>
    <%= f.email_field :email, class: "form-control form-control-lg", placeholder: "Enter your email address" %>
  </div>
  <div class="mb-3">
    <%= f.label :password, class: "form-label" %>
    <%= f.password_field :password, class: "form-control form-control-lg", placeholder: "Enter your password" %>
  </div>

  <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-success mb-3") %>

<% end %>

app/views/users/edit.html.erb
<h1 class="display-1">Edit user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="display-1">Authors</h1>
<% @users.each do |u| %>
<div class="row">
  <div class="row">
    <div class="col-8 mt-4">
      <div class="card shadow mb-5 bg-body rounded">
        <div class="card-header">
          Name: <%= u.username %>
        </div>
        <div class="card-body">
          <%= gravatar_for u, size: 200 %>
          <%= link_to 'View', user_path(u), class: "btn btn-outline-primary" %>
          <% if logged_in? && current_user == u%>
          <%= link_to 'Edit', edit_user_path(u), class: "btn btn-outline-warning" %>
          <%= link_to 'Delete', user_path(u), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small><%= pluralize(u.articles.count, 'article') %></small>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<h1 class="display-1">Signup as a new user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="display-1">Profile for <%= @user.username %></h1>

<%= gravatar_for @user, size: 200 %>

<%= render 'articles/articles_list' %>